---
- hosts: 192.168.1.44
  gather_facts: no
  tasks:
  - win_dns_client:
      adapter_names: '*'
      ipv4_addresses: 192.168.1.99

  - win_domain_membership:
       dns_domain_name: oraculum.com 
       hostname: Fortune500
       domain_admin_user: oraculum\administrator
       domain_admin_password: Apple@123
       state: domain
       register: dmout

  - win_reboot:




