---
- hosts: 192.168.1.44
- name: Install all security, critical, and rollup updates
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes
