- name: install mariadb server package (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
   name: mariadb-server
   state: latest
   when: ansible_distribution == "Ubuntu"

- name: install mariadb server package (CentOS)
  tags: centos,db,mariadb
  dnf:
   name: mariadb-server
   state: latest
   when: ansible_distribution == "CentOS"
